### ISSUE TITLE
Does not work with newer versions of QGIS on Windows (but fine with older ones)

### ISSUE THREAD

**Issue by Geogoeroe** [PrathamGitHub/NITK_RS-GIS_17#10]
Using QGIS 3.20, the plugin returns an error on loading:

2021-08-27T08:04:27     CRITICAL    Traceback (most recent call last):
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users/erik/AppData/Roaming/QGIS/QGIS3\profiles\aug21/python/plugins\NITK_RS-GIS_17\__init__.py", line 34, in classFactory
              from .RSGIS_M import RSGIS
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 799, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/erik/AppData/Roaming/QGIS/QGIS3\profiles\aug21/python/plugins\NITK_RS-GIS_17\RSGIS_M.py", line 57, in 
              import gdal
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 799, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'gdal'

As far  as I've tested, this error appears in all versions of QGIS that use the newer installers (msi). The plugin runs fine with versions of QGIS that were installed using the old exe installers... So it runs on 3.18 or earlier. But not on the 3.16 ltr that I recently installed.

I asked in the QGIS Community Telegram group, Tim Sutton noted that there are some changes to the way modules are imported. "from osgeo import gdal" is the new style, as opposed to "import gdal". Changed that, another python error came up, so I guess there are more similar issues. Not a programmer myself, this is as far as I can bugfix, otherwise would have helped out further.

**Comment by Geogoeroe** [comment]
Pull request made, was a simple fix after all (with help from @rduivenvoorde)

**Comment by PrathamGitHub** [comment]
Hi .. The issue is resolved in upcoming version .. Thanks :)
