### ISSUE TITLE
ModuleNotFoundError: No module named 'gdal'  on Mac OS

### ISSUE THREAD

**Issue by australgis** [PrathamGitHub/NITK_RS-GIS_17#12]
**ModuleNotFoundError: No module named 'gdal'** 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/australgis/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/NITK_RS-GIS_17/__init__.py", line 34, in classFactory
    from .RSGIS_M import RSGIS
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/australgis/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/NITK_RS-GIS_17/RSGIS_M.py", line 57, in 
    import gdal
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'gdal'

**Comment by Remmargyp** [comment]
Would very much enjoy a fix for this. https://gis.stackexchange.com/questions/413708/qgis-3-20-cant-load-plugin-directionalslope-no-module-named-gdal-on-windows/413712?noredirect=1#comment672775_413712 suggests edits to the code but import problems remain

**Comment by PrathamGitHub** [comment]
Hi .. this issue is resolved in upcoming version .. Thanks :)

**Comment by Marwe** [comment]
I just tried to fix this, because I had an outdated version.  Did it like in the following, see comment [gdal ... to support
both old and new versions](https://github.com/ikotarid/Terminus/issues/3#issuecomment-1132636821)

Not exactly necessary, as everything works fine here, but might be more robust in other environments?

```diff
diff --git a/RSGIS_M.py b/RSGIS_M.py
index 3886ba1..23d4f3a 100644
--- a/RSGIS_M.py
+++ b/RSGIS_M.py
@@ -38,13 +38,17 @@ import tarfile
 import zipfile
 import re
 import math
-from osgeo import gdal
+try:
+    import gdal
+except:
+    from osgeo import gdal
 import numpy as np
 import os
 from osgeo import ogr, osr
-
-from osgeo.gdalconst import GA_ReadOnly
-
+try:
+    from gdalconst import GA_ReadOnly
+except:
+    from osgeo.gdalconst import GA_ReadOnly
 import multiprocessing
 from io import StringIO
 import tokenize
```
