### ISSUE TITLE
Errors in calculating LST

### ISSUE THREAD

**Issue by yoshida-gisc** [PrathamGitHub/NITK_RS-GIS_17#13]
When I try to calculate Land Surface Temperature, I face the issue below which is also posted in https://gis.stackexchange.com/questions/390333/rs-gis-qgis-plugin-not-producing-land-surface-temperature-layer . How can we solve it?

```
Traceback (most recent call last):
File "C:/Users/Acer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NITK_RS-GIS_17\RSGIS_M.py", line 2147, in run

    lst_cal_w_del(num)

File "C:/Users/Acer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NITK_RS-GIS_17\RSGIS_M.py", line 1850, in lst_cal_w_del

    temp_cal(num)

File "C:/Users/Acer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NITK_RS-GIS_17\RSGIS_M.py", line 1804, in temp_cal

    (metadata_required[num][3][0][1] / output_ra[num][t_info[1][1]]) + 1)) - 273.15

TypeError: unsupported operand type(s) for /: 'float' and 'list'
```

**Comment by PrathamGitHub** [comment]
Hi .. Can you please share if you still face the same problem ?
