### ISSUE TITLE
The plugin doesn't work

### ISSUE THREAD

**Issue by taras-user** [PrathamGitHub/NITK_RS-GIS_17#8]
Hi,
I work on Ubuntu 20.04 and QGIS 3.10.10-A, pip 20.2.3 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8) 
I have some problem with this plug-in when I try to start it.
I attach the windows with the problem.
Can you tell me what I need to do?
Thanks!
`:-( Error:

 Traceback (most recent call last):
  File "/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/NITK_RS-GIS_17/RSGIS_M.py", line 2147, in run
    lst_cal_w_del(num)
  File "/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/NITK_RS-GIS_17/RSGIS_M.py", line 1850, in lst_cal_w_del
    temp_cal(num)
  File "/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/NITK_RS-GIS_17/RSGIS_M.py", line 1804, in temp_cal
    (metadata_required[num][3][0][1] / output_ra[num][t_info[1][1]]) + 1)) - 273.15
TypeError: unsupported operand type(s) for /: 'float' and 'list'
`

**Comment by LuisSevillano** [comment]
Hi! First of all, thank you for your effort developing this QGIS plugin. I have the same issue about that `metadata_required ` error. Any ideas?

**Comment by PrathamGitHub** [comment]
Sorry for delayed response .. but I could not recreate the error ... Can you please inform me if the problem still persists?

**Comment by PrathamGitHub** [comment]
> Hi! First of all, thank you for your effort developing this QGIS plugin. I have the same issue about that `metadata_required ` error. Any ideas?
Please make sure that selected files include metadata file also.
